@host = http://localhost:5178
@boardGameId = 69e755146b69bf706a67cbb6

###
# 1) GET all
GET {{host}}/api/boardgames
Accept: application/json

###
# 2) GET by id
GET {{host}}/api/boardgames/{{boardGameId}}
Accept: application/json

###
# 3) POST create
POST {{host}}/api/boardgames
Content-Type: application/json

{
  "title": "Catan",
  "publisher": "Kosmos",
  "minPlayers": 3,
  "maxPlayers": 4,
  "estimatedPlayTime": 90,
  "category": "Strategy"
}

###
# 4) PUT update
PUT {{host}}/api/boardgames/{{boardGameId}}
Content-Type: application/json

{
  "title": "Terraforming Mars",
  "publisher": "FryxGames",
  "minPlayers": 1,
  "maxPlayers": 5,
  "estimatedPlayTime": 120,
  "category": "Engine Building"
}

###
# 5) DELETE
DELETE {{host}}/api/boardgames/{{boardGameId}}
